version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: api
      DB_USERNAME: laravel
      DB_PASSWORD: laravelpass
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
